<?php

/**
 * This file is part of the package magicsunday/imagemeta.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

namespace MagicSunday\ImageMeta\Tests\Parse\Tiff;

use MagicSunday\ImageMeta\Core\BitMask;
use MagicSunday\ImageMeta\Core\BoundsError;
use MagicSunday\ImageMeta\Core\Endian;
use MagicSunday\ImageMeta\Core\MemoryBuffer;
use MagicSunday\ImageMeta\Core\ParseError;
use MagicSunday\ImageMeta\Core\Util\UInt64;
use MagicSunday\ImageMeta\Core\Util\Unpack;
use MagicSunday\ImageMeta\Model\Exif\ExifNumericList;
use MagicSunday\ImageMeta\Model\Exif\ExifRational;
use MagicSunday\ImageMeta\Model\Exif\ExifRationalList;
use MagicSunday\ImageMeta\Model\Exif\Ifd;
use MagicSunday\ImageMeta\Model\Exif\IfdEntry;
use MagicSunday\ImageMeta\Model\Exif\ParsedExif;
use MagicSunday\ImageMeta\Parse\Tiff\TiffConst;
use MagicSunday\ImageMeta\Parse\Tiff\TiffExifParser;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\Attributes\UsesClass;
use PHPUnit\Framework\TestCase;

use function pack;
use function str_repeat;
use function strlen;

/**
 * Fuzz-style tests for TiffExifParser using edge cases and malformed inputs.
 *
 * These tests simulate the kind of inputs that might be generated by fuzzing tools,
 * ensuring the parser handles corrupted, truncated, or maliciously crafted data
 * without crashing or entering infinite loops.
 *
 * EXIF 3.0 §4.5 and TIFF 6.0 define the structures that are intentionally violated here.
 */
#[CoversClass(TiffExifParser::class)]
#[UsesClass(MemoryBuffer::class)]
#[UsesClass(BitMask::class)]
#[UsesClass(Endian::class)]
#[UsesClass(UInt64::class)]
#[UsesClass(Unpack::class)]
#[UsesClass(BoundsError::class)]
#[UsesClass(ParseError::class)]
#[UsesClass(ExifRational::class)]
#[UsesClass(ExifRationalList::class)]
#[UsesClass(ExifNumericList::class)]
#[UsesClass(Ifd::class)]
#[UsesClass(IfdEntry::class)]
#[UsesClass(ParsedExif::class)]
#[UsesClass(TiffConst::class)]
final class TiffExifParserFuzzTest extends TestCase
{
    /**
     * Verifies that empty input raises BoundsError.
     *
     * @return void
     */
    #[Test]
    public function rejectsEmptyBlob(): void
    {
        $reader = new TiffExifParser();

        $this->expectException(BoundsError::class);

        $reader->parseFromBlob('');
    }

    /**
     * Verifies that too-short headers raise BoundsError.
     *
     * @return void
     */
    #[Test]
    public function rejectsTooShortBlob(): void
    {
        $blob = 'II';  // Only byte order marker

        $reader = new TiffExifParser();

        $this->expectException(BoundsError::class);

        $reader->parseFromBlob($blob);
    }

    /**
     * Verifies that random bytes raise ParseError.
     *
     * @return void
     */
    #[Test]
    public function rejectsRandomGarbage(): void
    {
        $blob = str_repeat("\xFF", 100);

        $reader = new TiffExifParser();

        $this->expectException(ParseError::class);

        $reader->parseFromBlob($blob);
    }

    /**
     * Verifies that all-null payloads raise ParseError.
     *
     * @return void
     */
    #[Test]
    public function rejectsNullBytes(): void
    {
        $blob = str_repeat("\x00", 100);

        $reader = new TiffExifParser();

        $this->expectException(ParseError::class);

        $reader->parseFromBlob($blob);
    }

    /**
     * Verifies that headers without IFD offsets raise BoundsError.
     *
     * @return void
     */
    #[Test]
    public function rejectsHeaderOnlyBlob(): void
    {
        $blob = 'II' . pack('v', TiffConst::MAGIC_CLASSIC);
        // Missing first IFD offset

        $reader = new TiffExifParser();

        $this->expectException(BoundsError::class);

        $reader->parseFromBlob($blob);
    }

    /**
     * Verifies that oversized entry counts raise BoundsError.
     *
     * @return void
     */
    #[Test]
    public function rejectsEntryWithOverflowCount(): void
    {
        $blob = 'II'
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);

        $blob .= pack('v', 1);  // 1 entry

        // Entry with huge count (INT_MAX)
        $blob .= pack('v', 0x0100)                // Tag
            . pack('v', TiffConst::TYPE_BYTE)     // Type: BYTE (1 byte each)
            . pack('V', 0x7FFFFFFF)               // Count: INT_MAX
            . pack('V', 100);                     // Offset

        $blob .= pack('V', 0);

        $reader = new TiffExifParser();

        $this->expectException(BoundsError::class);

        $reader->parseFromBlob($blob);
    }

    /**
     * Verifies that overlapping entry offsets are tolerated.
     *
     * @return void
     */
    #[Test]
    public function handlesOverlappingEntryData(): void
    {
        $blob = 'II'
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);

        $blob .= pack('v', 2);  // 2 entries

        // Both entries point to same offset (overlapping)
        $blob .= pack('v', 0x010F)                 // Tag: Manufacturer
            . pack('v', TiffConst::TYPE_ASCII)
            . pack('V', 10)
            . pack('V', 100);                      // Offset 100

        $blob .= pack('v', 0x0110)                 // Tag: Model
            . pack('v', TiffConst::TYPE_ASCII)
            . pack('V', 10)
            . pack('V', 100);                      // Same offset

        $blob .= pack('V', 0);

        // Pad to offset 100 and add data
        $blob .= str_repeat("\x00", 100 - strlen($blob));
        $blob .= "TestData\0\0";

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);

        // Should parse without error (overlapping is allowed, just reads same data twice)
    }

    /**
     * Verifies that 0/0 RATIONAL values do not crash parsing.
     *
     * @return void
     */
    #[Test]
    public function handlesRationalBothZero(): void
    {
        $blob = $this->buildTiffWithRational(0, 0);

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Verifies that maximum RATIONAL values do not crash parsing.
     *
     * @return void
     */
    #[Test]
    public function handlesRationalMaxValues(): void
    {
        $blob = $this->buildTiffWithRational(0xFFFFFFFF, 0xFFFFFFFF);

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Verifies that SRATIONAL values allow negative numerators.
     *
     * @return void
     */
    #[Test]
    public function handlesSrationalNegativeNumerator(): void
    {
        $blob = $this->buildTiffWithSRational(-12345, 67890);

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Verifies that SRATIONAL values allow negative denominators.
     *
     * @return void
     */
    #[Test]
    public function handlesSrationalNegativeDenominator(): void
    {
        $blob = $this->buildTiffWithSRational(12345, -67890);

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Verifies that SRATIONAL values allow both parts negative.
     *
     * @return void
     */
    #[Test]
    public function handlesSrationalBothNegative(): void
    {
        $blob = $this->buildTiffWithSRational(-12345, -67890);

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Verifies that deep IFD chains resolve subsequent offsets.
     *
     * @return void
     */
    #[Test]
    public function handlesDeepIfdChain(): void
    {
        // Create a chain of 5 IFDs
        $blob = 'II'
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);  // First IFD at 8

        $offset = 8;
        for ($i = 0; $i < 5; ++$i) {
            $blob .= pack('v', 0);  // 0 entries
            $nextOffset = $offset + 6;
            $blob .= pack('V', $i < 4 ? $nextOffset : 0);  // Next IFD or 0
            $offset = $nextOffset;
        }

        $reader = new TiffExifParser();
        $result = $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);

        self::assertCount(4, $result->subsequentIfds());
    }

    /**
     * Verifies that ASCII values containing embedded nulls are accepted.
     *
     * @return void
     */
    #[Test]
    public function handlesAsciiWithEmbeddedNulls(): void
    {
        $blob = 'II'
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);

        $blob .= pack('v', 1);

        $asciiData = "Test\x00String\x00";

        $blob .= pack('v', 0x010F)                 // Manufacturer
            . pack('v', TiffConst::TYPE_ASCII)
            . pack('V', strlen($asciiData))
            . pack('V', 26);

        $blob .= pack('V', 0);
        $blob .= $asciiData;

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Verifies that zero-count entries are accepted without error.
     *
     * @return void
     */
    #[Test]
    public function handlesEntryWithZeroCount(): void
    {
        $blob = 'II'
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);

        $blob .= pack('v', 1);

        $blob .= pack('v', 0x0100)             // ImageWidth
            . pack('v', TiffConst::TYPE_LONG)
            . pack('V', 0)                     // Count: 0
            . pack('V', 0);

        $blob .= pack('V', 0);

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Verifies that byte order follows the header endianness marker.
     *
     * @return void
     */
    #[Test]
    public function parsesMixedEndianness(): void
    {
        $blob = 'II'  // Little-endian marker
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);

        $blob .= pack('v', 1);

        // Entry with value that looks like big-endian but should be parsed as little-endian
        $blob .= pack('v', 0x0100)
            . pack('v', TiffConst::TYPE_LONG)
            . pack('V', 1)
            . pack('V', 0x01020304);  // Will be read as little-endian

        $blob .= pack('V', 0);

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Verifies that undefined-type byte arrays are accepted as-is.
     *
     * @return void
     */
    #[Test]
    public function handlesUndefinedTypeWithRandomBytes(): void
    {
        $blob = 'II'
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);

        $blob .= pack('v', 1);

        $undefinedData = "\x00\xFF\x01\xFE\x02\xFD\x03\xFC";

        $blob .= pack('v', 0x9000)                    // ExifVersion
            . pack('v', TiffConst::TYPE_UNDEFINED)
            . pack('V', strlen($undefinedData))
            . pack('V', 26);

        $blob .= pack('V', 0);
        $blob .= $undefinedData;

        $reader = new TiffExifParser();
        $reader->parseFromBlob($blob);

        $this->addToAssertionCount(1);
    }

    /**
     * Builds a TIFF blob with a RATIONAL value.
     *
     * @param int $numerator   Numerator.
     * @param int $denominator Denominator.
     *
     * @return string Binary TIFF blob.
     */
    private function buildTiffWithRational(int $numerator, int $denominator): string
    {
        $blob = 'II'
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);

        $blob .= pack('v', 1);

        $blob .= pack('v', 0x011A)                    // XResolution
            . pack('v', TiffConst::TYPE_RATIONAL)
            . pack('V', 1)
            . pack('V', 26);

        $blob .= pack('V', 0);

        return $blob . (pack('V', $numerator) . pack('V', $denominator));
    }

    /**
     * Builds a TIFF blob with an SRATIONAL value.
     *
     * @param int $numerator   Signed numerator.
     * @param int $denominator Signed denominator.
     *
     * @return string Binary TIFF blob.
     */
    private function buildTiffWithSRational(int $numerator, int $denominator): string
    {
        $blob = 'II'
            . pack('v', TiffConst::MAGIC_CLASSIC)
            . pack('V', 8);

        $blob .= pack('v', 1);

        $blob .= pack('v', 0x9201)                    // ShutterSpeedValue
            . pack('v', TiffConst::TYPE_SRATIONAL)
            . pack('V', 1)
            . pack('V', 26);

        $blob .= pack('V', 0);

        return $blob . (pack('l', $numerator) . pack('l', $denominator));
    }
}
